# documentation: https://github.com/henrygd/beszel?tab=readme-ov-file#getting-started
# slogan: A lightweight server resource monitoring hub with historical data, docker stats, and alerts.
# category: monitoring
# tags: beszel,monitoring,server,stats,alerts
# logo: svgs/beszel.svg
# port: 8090

# When adding a System in the UI, the Host/IP must be beszel-agent (or the container name, ex: beszel-agent-pswog4s8wks4o8osw44cw0k8)
# Add the public Key in "Key" env variable and token in the "Token" variable below (These are obtained from Beszel UI)
services:
  beszel:
    image: 'henrygd/beszel:0.12.10'
    environment:
      - SERVICE_URL_BESZEL_8090
    volumes:
      - 'beszel_data:/beszel_data'
      - 'beszel_socket:/beszel_socket'
  beszel-agent:
    image: 'henrygd/beszel-agent:0.12.10'
    volumes:
      - beszel_agent_data:/var/lib/beszel-agent
      - beszel_socket:/beszel_socket
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      - LISTEN=/beszel_socket/beszel.sock
      - HUB_URL=http://beszel:8090
      - 'TOKEN=${TOKEN}'
      - 'KEY=${KEY}'

