# documentation: https://homarr.dev
# slogan: Homarr is a self-hosted homepage for your services.
# category: productivity
# tags: homarr,self-hosted,homepage
# logo: svgs/homarr.svg
# port: 7575

services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:v1.40.0
    environment:
      - SERVICE_URL_HOMARR_7575
      - SERVICE_HEX_32_HOMARR
      - 'SECRET_ENCRYPTION_KEY=${SERVICE_HEX_32_HOMARR}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homarr/appdata:/appdata
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:7575"]
      interval: 5s
      timeout: 20s
      retries: 10
